### ISSUE TITLE
No PDB support! j/k

### ISSUE THREAD

**Issue by arizvisa** [danigargu/syms2elf#1]
Please please please do something for pdb too!! :-P
All of us windows people could really a tool that emits symbols from ida ;-)

Anyways though, glad to see someone else thought of using symbols to share data between multiple tools. Awesome script.

<3

**Comment by Manouchehri** [comment]
These projects might be a good starting point.
- https://github.com/karstenBriksoft/SymTabCreator
- https://github.com/rainers/cv2pdb
